/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSolutionsRouteImport } from './routes/_authenticated/solutions'
import { Route as AuthenticatedProcessRouteImport } from './routes/_authenticated/process'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolutionsRoute = AuthenticatedSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessRoute = AuthenticatedProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/contact': typeof AuthenticatedContactRoute
  '/process': typeof AuthenticatedProcessRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/contact': typeof AuthenticatedContactRoute
  '/process': typeof AuthenticatedProcessRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/process': typeof AuthenticatedProcessRoute
  '/_authenticated/solutions': typeof AuthenticatedSolutionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/about' | '/contact' | '/process' | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/about' | '/contact' | '/process' | '/solutions' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/about'
    | '/_authenticated/contact'
    | '/_authenticated/process'
    | '/_authenticated/solutions'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solutions': {
      id: '/_authenticated/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof AuthenticatedSolutionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/process': {
      id: '/_authenticated/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof AuthenticatedProcessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedProcessRoute: typeof AuthenticatedProcessRoute
  AuthenticatedSolutionsRoute: typeof AuthenticatedSolutionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedProcessRoute: AuthenticatedProcessRoute,
  AuthenticatedSolutionsRoute: AuthenticatedSolutionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
